"""add_batch_number_to_haccp_assessment_items

Revision ID: 0c19cd66f2fd
Revises: c7dcca2dff09
Create Date: 2026-05-14 11:21:00.802922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c19cd66f2fd'
down_revision: Union[str, Sequence[str], None] = 'c7dcca2dff09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('haccp_audit_details', schema='sct_iso')
    op.drop_table('haccp_audits', schema='sct_iso')
    op.drop_table('haccp_checklist_templates', schema='sct_iso')
    op.add_column('haccp_assessment_items', sa.Column('batch_number', sa.String(length=100), nullable=True), schema='sct_iso')
    op.drop_index(op.f('ix_haccp_assessment_items_assessment_id'), table_name='haccp_assessment_items', schema='sct_iso')
    op.drop_index(op.f('ix_haccp_assessments_haccp_plan_id'), table_name='haccp_assessments', schema='sct_iso')
    op.drop_index(op.f('ix_haccp_assessments_org_id'), table_name='haccp_assessments', schema='sct_iso')
    op.drop_index(op.f('ix_haccp_assessments_status'), table_name='haccp_assessments', schema='sct_iso')
    op.drop_column('haccp_assessments', 'corrective_actions', schema='sct_iso')
    op.drop_column('haccp_assessments', 'reviewer_notes', schema='sct_iso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('haccp_assessments', sa.Column('reviewer_notes', sa.TEXT(), autoincrement=False, nullable=True), schema='sct_iso')
    op.add_column('haccp_assessments', sa.Column('corrective_actions', sa.TEXT(), autoincrement=False, nullable=True), schema='sct_iso')
    op.create_index(op.f('ix_haccp_assessments_status'), 'haccp_assessments', ['status'], unique=False, schema='sct_iso')
    op.create_index(op.f('ix_haccp_assessments_org_id'), 'haccp_assessments', ['org_id'], unique=False, schema='sct_iso')
    op.create_index(op.f('ix_haccp_assessments_haccp_plan_id'), 'haccp_assessments', ['haccp_plan_id'], unique=False, schema='sct_iso')
    op.create_index(op.f('ix_haccp_assessment_items_assessment_id'), 'haccp_assessment_items', ['assessment_id'], unique=False, schema='sct_iso')
    op.drop_column('haccp_assessment_items', 'batch_number', schema='sct_iso')
    op.create_table('haccp_checklist_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('haccp_plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('requirement', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['haccp_plan_id'], ['sct_iso.haccp_plans.id'], name=op.f('haccp_checklist_templates_haccp_plan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], name=op.f('haccp_checklist_templates_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('haccp_checklist_templates_pkey')),
    schema='sct_iso'
    )
    op.create_table('haccp_audits',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('haccp_plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('audit_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('overall_result', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('auditor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['sct_iso.users.id'], name=op.f('haccp_audits_auditor_id_fkey')),
    sa.ForeignKeyConstraint(['haccp_plan_id'], ['sct_iso.haccp_plans.id'], name=op.f('haccp_audits_haccp_plan_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], name=op.f('haccp_audits_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('haccp_audits_pkey')),
    schema='sct_iso'
    )
    op.create_table('haccp_audit_details',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('audit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('checklist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('observation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidence_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['sct_iso.haccp_audits.id'], name=op.f('haccp_audit_details_audit_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checklist_id'], ['sct_iso.haccp_checklist_templates.id'], name=op.f('haccp_audit_details_checklist_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('haccp_audit_details_pkey')),
    schema='sct_iso'
    )
    # ### end Alembic commands ###
