"""Add HACCP Audit system

Revision ID: 50fbc80d5199
Revises: 1101818a45c9
Create Date: 2026-05-07 14:15:31.963610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50fbc80d5199'
down_revision: Union[str, Sequence[str], None] = '1101818a45c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haccp_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('haccp_plan_id', sa.UUID(), nullable=False),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_result', sa.String(length=50), nullable=True),
    sa.Column('auditor_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['haccp_plan_id'], ['sct_iso.haccp_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('haccp_checklist_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('haccp_plan_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_type', sa.String(length=50), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['haccp_plan_id'], ['sct_iso.haccp_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('haccp_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('haccp_plan_id', sa.UUID(), nullable=False),
    sa.Column('verification_type', sa.String(length=50), nullable=True),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('conclusion', sa.String(length=50), nullable=True),
    sa.Column('report_url', sa.String(length=500), nullable=True),
    sa.Column('conducted_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('conducted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['conducted_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['haccp_plan_id'], ['sct_iso.haccp_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('haccp_audit_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['sct_iso.haccp_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checklist_id'], ['sct_iso.haccp_checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.alter_column('ccp_monitoring_logs', 'deviation_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=True,
               schema='sct_iso')
    op.alter_column('haccp_plan_versions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               schema='sct_iso')
    op.alter_column('prp_audit_details', 'result',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               existing_nullable=False,
               schema='sct_iso')
    op.add_column('prp_checklist_templates', sa.Column('location_id', sa.UUID(), nullable=True), schema='sct_iso')
    op.add_column('prp_checklist_templates', sa.Column('answer_type', sa.String(length=50), nullable=False), schema='sct_iso')
    op.add_column('prp_checklist_templates', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='sct_iso')
    op.add_column('prp_checklist_templates', sa.Column('target_value', sa.Numeric(precision=10, scale=2), nullable=True), schema='sct_iso')
    op.create_foreign_key(None, 'prp_checklist_templates', 'locations', ['location_id'], ['id'], source_schema='sct_iso', referent_schema='sct_iso')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prp_checklist_templates', schema='sct_iso', type_='foreignkey')
    op.drop_column('prp_checklist_templates', 'target_value', schema='sct_iso')
    op.drop_column('prp_checklist_templates', 'options', schema='sct_iso')
    op.drop_column('prp_checklist_templates', 'answer_type', schema='sct_iso')
    op.drop_column('prp_checklist_templates', 'location_id', schema='sct_iso')
    op.alter_column('prp_audit_details', 'result',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               schema='sct_iso')
    op.alter_column('haccp_plan_versions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               schema='sct_iso')
    op.alter_column('ccp_monitoring_logs', 'deviation_status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               schema='sct_iso')
    op.drop_table('haccp_audit_details', schema='sct_iso')
    op.drop_table('haccp_verifications', schema='sct_iso')
    op.drop_table('haccp_checklist_templates', schema='sct_iso')
    op.drop_table('haccp_audits', schema='sct_iso')
    # ### end Alembic commands ###
