"""baseline_init

Revision ID: 5e28a4a66bed
Revises: 
Create Date: 2026-04-22 16:33:25.384510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e28a4a66bed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS sct_iso")
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='sct_iso'
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='sct_iso'
    )
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.String(length=100), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('insight_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('document_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('standard', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['sct_iso.document_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('iot_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('device_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_code'),
    schema='sct_iso'
    )
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('period_type', sa.String(length=20), nullable=False),
    sa.Column('doc_total', sa.Integer(), nullable=True),
    sa.Column('doc_approved', sa.Integer(), nullable=True),
    sa.Column('doc_pending', sa.Integer(), nullable=True),
    sa.Column('doc_overdue_review', sa.Integer(), nullable=True),
    sa.Column('haccp_ccp_monitored_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('haccp_deviation_count', sa.Integer(), nullable=True),
    sa.Column('prp_audit_compliance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('prp_nc_open_count', sa.Integer(), nullable=True),
    sa.Column('capa_ontime_closure_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('capa_open_count', sa.Integer(), nullable=True),
    sa.Column('capa_overdue_count', sa.Integer(), nullable=True),
    sa.Column('alert_critical_count', sa.Integer(), nullable=True),
    sa.Column('alert_open_count', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='sct_iso'
    )
    op.create_table('prp_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('standard_ref', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_roles_org_name'),
    schema='sct_iso'
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['sct_iso.iot_devices.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['sct_iso.permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sct_iso.roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions'),
    schema='sct_iso'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['sct_iso.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='sct_iso'
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['sct_iso.users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('doc_code', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('current_version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_period', sa.Integer(), nullable=False),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['sct_iso.document_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('haccp_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['sct_iso.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('non_conformities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('nc_code', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_ref_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('detected_by', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detected_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sct_iso.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('prp_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('prp_program_id', sa.UUID(), nullable=True),
    sa.Column('area_id', sa.UUID(), nullable=True),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('total_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('compliance_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_result', sa.String(length=50), nullable=True),
    sa.Column('auditor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['sct_iso.locations.id'], ),
    sa.ForeignKeyConstraint(['auditor_id'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prp_program_id'], ['sct_iso.prp_programs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('device_label', sa.String(length=128), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sct_iso.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='sct_iso'
    )
    op.create_table('report_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_roles', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('filter_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schedule_type', sa.String(length=50), nullable=True),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recipients', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('output_format', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['sct_iso.roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sct_iso.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_roles'),
    schema='sct_iso'
    )
    op.create_table('capas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('nc_id', sa.UUID(), nullable=True),
    sa.Column('capa_code', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['nc_id'], ['sct_iso.non_conformities.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['sct_iso.documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('process_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('haccp_plan_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=True),
    sa.Column('is_ccp', sa.Boolean(), nullable=False),
    sa.Column('parent_step_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['haccp_plan_id'], ['sct_iso.haccp_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_step_id'], ['sct_iso.process_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('prp_checklist_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prp_program_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['sct_iso.documents.id'], ),
    sa.ForeignKeyConstraint(['prp_program_id'], ['sct_iso.prp_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('report_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('config_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('report_name', sa.String(length=255), nullable=True),
    sa.Column('period_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('file_format', sa.String(length=20), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('sent_to', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['sct_iso.report_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['sct_iso.organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('hazard_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('hazard_type', sa.String(length=50), nullable=False),
    sa.Column('hazard_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('control_measure', sa.Text(), nullable=True),
    sa.Column('is_significant', sa.Boolean(), nullable=False),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['step_id'], ['sct_iso.process_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('prp_audit_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['sct_iso.prp_audits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['checklist_id'], ['sct_iso.prp_checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('ccps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('haccp_plan_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('hazard_id', sa.UUID(), nullable=True),
    sa.Column('ccp_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('critical_limit', sa.Text(), nullable=False),
    sa.Column('monitoring_method', sa.String(length=255), nullable=True),
    sa.Column('monitoring_frequency', sa.String(length=100), nullable=True),
    sa.Column('monitoring_device', sa.String(length=255), nullable=True),
    sa.Column('responsible_user', sa.UUID(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('verification_procedure', sa.Text(), nullable=True),
    sa.Column('ai_suggestion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['haccp_plan_id'], ['sct_iso.haccp_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hazard_id'], ['sct_iso.hazard_analyses.id'], ),
    sa.ForeignKeyConstraint(['responsible_user'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['sct_iso.process_steps.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    op.create_table('ccp_monitoring_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ccp_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('shift', sa.String(length=50), nullable=True),
    sa.Column('measured_value', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('is_within_limit', sa.Boolean(), nullable=True),
    sa.Column('deviation_note', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('iot_device_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['ccp_id'], ['sct_iso.ccps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['sct_iso.users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['sct_iso.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='sct_iso'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ccp_monitoring_logs', schema='sct_iso')
    op.drop_table('ccps', schema='sct_iso')
    op.drop_table('prp_audit_details', schema='sct_iso')
    op.drop_table('hazard_analyses', schema='sct_iso')
    op.drop_table('report_history', schema='sct_iso')
    op.drop_table('prp_checklist_templates', schema='sct_iso')
    op.drop_table('process_steps', schema='sct_iso')
    op.drop_table('document_versions', schema='sct_iso')
    op.drop_table('capas', schema='sct_iso')
    op.drop_table('user_roles', schema='sct_iso')
    op.drop_table('report_configs', schema='sct_iso')
    op.drop_table('refresh_tokens', schema='sct_iso')
    op.drop_table('prp_audits', schema='sct_iso')
    op.drop_table('notification_logs', schema='sct_iso')
    op.drop_table('non_conformities', schema='sct_iso')
    op.drop_table('haccp_plans', schema='sct_iso')
    op.drop_table('documents', schema='sct_iso')
    op.drop_table('calendar_events', schema='sct_iso')
    op.drop_table('audit_log', schema='sct_iso')
    op.drop_table('users', schema='sct_iso')
    op.drop_table('role_permissions', schema='sct_iso')
    op.drop_table('alerts', schema='sct_iso')
    op.drop_table('roles', schema='sct_iso')
    op.drop_table('prp_programs', schema='sct_iso')
    op.drop_table('products', schema='sct_iso')
    op.drop_table('locations', schema='sct_iso')
    op.drop_table('kpi_snapshots', schema='sct_iso')
    op.drop_table('iot_devices', schema='sct_iso')
    op.drop_table('document_categories', schema='sct_iso')
    op.drop_table('ai_analysis_results', schema='sct_iso')
    op.drop_table('permissions', schema='sct_iso')
    op.drop_table('organizations', schema='sct_iso')
    op.execute("DROP SCHEMA IF EXISTS sct_iso CASCADE")
    # ### end Alembic commands ###
